/**
 * export.js
 * Export utilities: Markdown daily report, JSON backup, CSV score history.
 */

import { storage } from './storage.js';
import { formatDate } from './dates.js';

/**
 * Generate a Markdown daily report for a given day.
 * @param {number} dayNum
 * @param {object} dayData - roadmap day object
 * @param {object} report - stored report
 * @param {Array} completedTasks - array of task IDs completed
 * @param {object} habits - habit check state
 * @param {number} score - day score
 * @returns {string} markdown string
 */
export function generateDayMarkdown(dayNum, dayData, report, completedTasks, habits, score) {
  const date = formatDate(new Date().toISOString().split('T')[0]);
  const tasks = dayData?.tasks || [];

  const taskLines = tasks.map(t =>
    `- [${completedTasks.includes(t.id) ? 'x' : ' '}] ${t.text}`
  ).join('\n');

  const habitLines = Object.entries(habits || {})
    .map(([name, done]) => `- [${done ? 'x' : ' '}] ${name}`)
    .join('\n');

  return `# Day ${dayNum} — ${dayData?.topic || 'Study Session'}

**Date:** ${date}
**Phase:** ${dayData?.phaseLabel || ''}
**Score:** +${score} pts
**Hours:** ${dayData?.isSunday ? '6h (Sunday)' : '4h'}

---

## ✅ Tasks

${taskLines || '- No tasks recorded'}

---

## 💡 What I Learned Today

${report?.learned || '_Not filled in._'}

---

## ⏳ What I Wasted Time On

${report?.wasted || '_Not filled in._'}

---

## 📝 Notes & Reflections

${report?.notes || '_Not filled in._'}

---

## 🎯 Tomorrow's Focus

${report?.tomorrow || '_Not filled in._'}

---

## 🔋 Habits

${habitLines || '- No habits tracked'}

---

**Frustration Level:** ${report?.frustration || 'N/A'} / 10

---
*Generated by CyberTrack v1.0 — 800-Day Purple Team Tracker*
`;
}

/**
 * Generate a weekly Markdown summary.
 * @param {number} weekNum
 * @param {Array} days - array of day objects for the week
 * @returns {string}
 */
export function generateWeeklySummary(weekNum, days) {
  const totalPts = days.reduce((sum, d) => sum + (d.score || 0), 0);
  const completed = days.filter(d => d.status === 'completed').length;
  const missed = days.filter(d => d.status === 'missed').length;

  const dayLines = days.map(d =>
    `| Day ${d.dayNum} | ${d.topic} | ${d.status} | +${d.score || 0} pts |`
  ).join('\n');

  return `# Week ${weekNum} Summary — CyberTrack

**Days Completed:** ${completed} / ${days.length}
**Days Missed:** ${missed}
**Week Score:** +${totalPts} pts

---

## Daily Breakdown

| Day | Topic | Status | Score |
|-----|-------|--------|-------|
${dayLines}

---
*Generated by CyberTrack v1.0*
`;
}

/**
 * Export all tracker data as a JSON blob and trigger download.
 */
export function exportJSONBackup() {
  const data = storage.exportAll();
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `cybertrack-backup-${new Date().toISOString().split('T')[0]}.json`);
}

/**
 * Export score history as CSV.
 */
export function exportScoreCSV() {
  const history = storage.getScoreHistory();
  const rows = [['Day', 'Points', 'Cumulative Score', 'Date']];
  history.forEach(entry => {
    rows.push([entry.day, entry.pts, entry.cumulative, entry.date || '']);
  });
  const csv = rows.map(r => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  triggerDownload(blob, `cybertrack-scores-${new Date().toISOString().split('T')[0]}.csv`);
}

/**
 * Copy text to clipboard.
 * @param {string} text
 * @returns {Promise<boolean>}
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback
    const el = document.createElement('textarea');
    el.value = text;
    el.style.position = 'fixed';
    el.style.opacity = '0';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    return true;
  }
}

/**
 * Trigger a file download in the browser.
 * @param {Blob} blob
 * @param {string} filename
 */
function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
