/**
 * generate-roadmap.js
 * Run: node scripts/generate-roadmap.js
 * Outputs: src/data/roadmap.json
 *
 * Generates all 800 days of structured task data organized by phase.
 * Edit the PHASE_CONTENT object below to customize tasks per topic.
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Phase definitions with topic blocks ──────────────────────────────────────
const PHASE_CONTENT = [
  // PHASE 1: Foundation (Days 1–100)
  {
    phase: 1,
    phaseLabel: "Foundation",
    color: "#4ade80",
    blocks: [
      {
        topic: "Cybersecurity Fundamentals & Mindset",
        days: 10,
        tasks: [
          "Read: CIA Triad, threat modeling, and the defender mindset — take structured notes",
          "Study: MITRE ATT&CK framework — navigate Navigator, understand tactics vs techniques",
          "Lab: Set up Kali Linux VM + snapshot strategy — document your lab setup",
          "Study: Cyber Kill Chain + Diamond Model — map a real APT campaign through both models",
          "Read: 'Penetration Testing' by Georgia Weidman Ch. 1–3",
          "Lab: Configure Burp Suite Community — intercept your first HTTP request",
          "Study: TCP/IP fundamentals — Wireshark capture and annotate a full HTTP session",
          "Lab: Set up home lab network — two VMs, isolated subnet, document the topology",
          "Read: OWASP Top 10 — 2021 edition, one vulnerability per hour",
          "Project: Write a 1-page threat model for a fictional web app — publish to GitHub",
        ]
      },
      {
        topic: "Python for Offensive & Defensive Security",
        days: 25,
        tasks: [
          "Python basics: data types, control flow, functions — build a password strength checker",
          "Python: file I/O + regex — parse /etc/passwd format, extract usernames",
          "Python: socket programming — build a TCP port scanner from scratch",
          "Python: add banner grabbing to your port scanner",
          "Python: build a simple HTTP request library using sockets (no requests yet)",
          "Python: argparse + logging — make your scanner a proper CLI tool",
          "Python: subprocess + os — automate nmap scans and parse XML output",
          "Python: build a log parser that identifies failed SSH login attempts",
          "Python: extend log parser to detect brute-force patterns (5+ fails in 60s)",
          "Python: CSV/JSON output — export findings from your tools",
          "Python: requests library — build a web scraper for a target URL",
          "Python: build a simple directory brute-forcer using requests + wordlist",
          "Python: threading — make your tools concurrent (10x speed improvement)",
          "Python: Scapy intro — craft and send a custom TCP SYN packet",
          "Python: Scapy — build an ARP scanner for your local subnet",
          "Python: hashlib — build a password hash identifier + cracker for MD5/SHA1",
          "Python: base64 + XOR — implement basic payload encoding",
          "Python: build a simple keylogger (Windows/Linux) — educational, local only",
          "Python: socket reverse shell — understand the mechanism completely",
          "Python: pwntools intro — interact with a simple binary over TCP",
          "Python: paramiko — build an SSH brute-force tool with delay + logging",
          "Python: build a simple SIEM alert parser that reads Splunk CSV exports",
          "Python: unittest — add tests to your port scanner",
          "Python: refactor all tools into a proper package structure",
          "Project: Publish your Python toolkit to GitHub with README and usage docs",
        ]
      },
      {
        topic: "Assembly Language & Low-Level Fundamentals",
        days: 15,
        tasks: [
          "Read: x86 architecture — registers, memory layout, stack, heap",
          "Lab: Set up NASM + GDB + pwndbg on your Kali VM",
          "Assembly: write Hello World in x86_64 NASM — understand every line",
          "Assembly: arithmetic operations, conditional jumps, loops",
          "Assembly: function calls — understand prologue/epilogue, calling conventions",
          "Assembly: stack manipulation — push/pop, stack frames",
          "Assembly: system calls — write a syscall to open/read a file",
          "Lab: GDB walkthrough — set breakpoints, step through, inspect registers",
          "Lab: disassemble a simple C program — compare C source vs assembly",
          "Assembly: strings and buffers — understand null terminators, buffer boundaries",
          "Lab: trace a shellcode sample (32-byte execve /bin/sh) — explain each instruction",
          "Lab: identify a buffer overflow manually in a vulnerable C program",
          "Lab: exploit a stack buffer overflow in a local lab binary (no ASLR/NX)",
          "Read: 'Hacking: The Art of Exploitation' Ch. 1–2",
          "Project: Write a 500-word annotated breakdown of a shellcode sample — publish",
        ]
      },
      {
        topic: "Log Analysis & SIEM Foundations",
        days: 10,
        tasks: [
          "Set up Splunk Free — ingest your Kali VM's auth.log and syslog",
          "Study: Windows Event Log — key event IDs (4624, 4625, 4648, 4672, 4768, 4769)",
          "Lab: Generate failed SSH logins — find them in Splunk with SPL queries",
          "Lab: Sysmon installation + config (SwiftOnSecurity config) on Windows VM",
          "Lab: Run Mimikatz on test VM — find the Sysmon events it generates",
          "Lab: Build a Splunk dashboard for authentication events",
          "Lab: Elastic Stack setup — ingest logs from a second VM",
          "Lab: Write 5 Splunk alerts for common attack patterns",
          "Lab: Correlate a simulated attack across 3 log sources",
          "Project: Write a detection write-up for one attack technique — attack + detection + SPL query",
        ]
      },
      {
        topic: "Web Application Security Labs",
        days: 20,
        tasks: [
          "DVWA: setup + configure all difficulty levels — document the process",
          "DVWA: SQL Injection (low) — manual exploitation + sqlmap",
          "DVWA: SQL Injection (medium + high) — bypass filters manually",
          "DVWA: XSS Reflected (all levels) — understand encoding bypasses",
          "DVWA: XSS Stored — steal a cookie via JavaScript payload",
          "DVWA: CSRF — forge a password change request",
          "DVWA: File Inclusion (LFI + RFI) — read /etc/passwd via LFI",
          "DVWA: File Upload — bypass extension checks to upload PHP shell",
          "DVWA: Command Injection — chain commands, escape filters",
          "DVWA: Brute Force — bypass + automate with Python",
          "JuiceShop: setup + complete first 10 challenges (1-star + 2-star)",
          "JuiceShop: authentication bypass challenges",
          "JuiceShop: broken access control — access admin page as low-priv user",
          "JuiceShop: XXE injection challenge",
          "JuiceShop: SSRF challenge",
          "JuiceShop: JWT manipulation challenges",
          "Burp Suite: Master Repeater, Intruder, Decoder — documented use cases",
          "Burp Suite: intercept + modify a login request — capture a full auth flow",
          "Web Security Challenge 1: complete all exercises",
          "Project: Write a full OWASP Top 10 walkthrough with your own examples — GitHub",
        ]
      },
      {
        topic: "Networking Deep-Dive",
        days: 10,
        tasks: [
          "Wireshark: capture + analyze a full TCP 3-way handshake — annotated screenshot",
          "Wireshark: identify ARP requests + responses in a capture",
          "Lab: ARP spoofing with arpspoof — capture traffic, observe in Wireshark",
          "Wireshark: analyze a DNS resolution sequence — annotate every packet",
          "Lab: DNS spoofing with dnsspoof — observe the redirect",
          "Wireshark: capture a full HTTP login — extract credentials from plaintext",
          "Wireshark: analyze HTTPS — observe TLS handshake, understand SNI",
          "Lab: nmap scanning techniques — SYN, connect, UDP, version detection, scripting",
          "Lab: build a network topology diagram of your lab environment",
          "Project: Wireshark analysis report — identify 3 attack patterns in a provided PCAP file",
        ]
      },
    ]
  },

  // PHASE 2: Offensive Core (Days 101–280)
  {
    phase: 2,
    phaseLabel: "Offensive Core",
    color: "#f87171",
    blocks: [
      {
        topic: "Active Directory Offensive",
        days: 40,
        tasks: [
          "AD Lab setup: 2 Domain Controllers + 3 workstations — document every step",
          "Study: AD structure — domains, forests, trusts, OUs, GPOs",
          "Study: Kerberos authentication flow — AS-REQ, TGT, TGS, AP-REQ",
          "Lab: Enumerate AD with BloodHound + SharpHound — collect all data",
          "Lab: Analyze BloodHound output — identify shortest path to Domain Admin",
          "Lab: PowerView enumeration — users, groups, computers, shares, GPOs",
          "Lab: LDAP queries — enumerate AD manually via ldapsearch",
          "Attack: LLMNR/NBT-NS poisoning with Responder — capture NTLMv2 hashes",
          "Attack: NTLM relay with ntlmrelayx — relay to a second target",
          "Attack: Password spraying — identify valid credentials without lockout",
          "Attack: Kerberoasting — extract SPN hashes, crack offline with hashcat",
          "Attack: AS-REP Roasting — identify AS-REP roastable accounts",
          "Attack: Pass-the-Hash with crackmapexec",
          "Attack: Pass-the-Ticket with Rubeus",
          "Attack: Overpass-the-Hash — convert NTLM to Kerberos TGT",
          "Attack: DCSync — extract krbtgt hash with secretsdump",
          "Attack: Golden Ticket — forge TGT with krbtgt hash",
          "Attack: Silver Ticket — forge service ticket",
          "Attack: ACL abuse — WriteDACL, GenericAll, GenericWrite exploitation",
          "Attack: Unconstrained delegation — extract TGTs from machine account",
          "Attack: Constrained delegation abuse",
          "Attack: Resource-based constrained delegation (RBCD)",
          "Attack: Forest trust attack — inter-forest ticket forgery",
          "Lab: Lateral movement via WMI, PSExec, WinRM",
          "Lab: Lateral movement via DCOM",
          "Lab: Full kill chain — phish to DA — document every step",
          "Lab: RTL Pro AD Lab 1 — complete all exercises",
          "Lab: CADP certification exercises",
          "Blue team: identify every attack above in Splunk — write detection for each",
          "Project: Full AD attack path report with BloodHound diagrams — GitHub portfolio",
          "Project: AD detection write-up — attack + Splunk query + Sigma rule for each technique",
          "Lab: Azure AD enumeration with AzureHound",
          "Lab: Azure AD attack — illicit consent grant",
          "Lab: Azure AD pass-through authentication abuse",
          "Lab: Azure AD PRT (Primary Refresh Token) theft",
          "Lab: Hybrid AD — sync from on-prem to Azure, attack the sync account",
          "Lab: Entra ID conditional access bypass",
          "Lab: Microsoft 365 attacks — mailbox access, Teams exfil",
          "Lab: Azure AD Purple Team — attack + detect cycle",
          "Project: Azure AD attack/detect report — publish as blog post",
        ]
      },
      {
        topic: "Privilege Escalation — Windows & Linux",
        days: 20,
        tasks: [
          "Windows PrivEsc: automated enumeration with WinPEAS",
          "Windows PrivEsc: unquoted service paths — exploit manually",
          "Windows PrivEsc: weak service permissions — replace binary",
          "Windows PrivEsc: AlwaysInstallElevated — MSI privilege abuse",
          "Windows PrivEsc: stored credentials — registry, files, memory",
          "Windows PrivEsc: token impersonation — SeImpersonatePrivilege",
          "Windows PrivEsc: PrintSpoofer / RoguePotato",
          "Windows PrivEsc: DLL hijacking — identify vulnerable apps",
          "Windows PrivEsc: scheduled tasks — weak permissions",
          "Windows PrivEsc: UAC bypass techniques — multiple methods",
          "Linux PrivEsc: automated enumeration with LinPEAS",
          "Linux PrivEsc: SUID binaries — GTFOBins exploitation",
          "Linux PrivEsc: sudo misconfigurations — sudoers abuse",
          "Linux PrivEsc: cron job abuse — writable scripts in PATH",
          "Linux PrivEsc: writable /etc/passwd — add root user",
          "Linux PrivEsc: NFS no_root_squash exploitation",
          "Linux PrivEsc: Docker escape — container breakout",
          "Linux PrivEsc: kernel exploit (CVE-2021-4034 Polkit)",
          "Windows Persistence: registry run keys, startup folder, scheduled tasks",
          "Project: Document 10 unique privesc paths (5 Windows + 5 Linux) — published write-ups",
        ]
      },
      {
        topic: "Spear Phishing, Initial Access & OpSec",
        days: 20,
        tasks: [
          "Study: phishing infrastructure — domains, redirectors, SSL certs",
          "Lab: Register a domain + configure DNS for phishing (use lab environment)",
          "Lab: GoPhish setup — campaign, template, tracking pixel",
          "Lab: craft a convincing phishing email — lure design, impersonation",
          "Lab: HTML smuggling payload delivery — bypass email gateways",
          "Lab: macro-enabled Office document — VBA payload generation",
          "Lab: bypass macro warnings with signed documents",
          "Lab: ISO/LNK delivery — Windows 11 mark-of-the-web bypass",
          "Lab: OneNote attachment delivery",
          "Lab: browser-in-the-browser (BitB) phishing page",
          "Study: OpSec for red teams — OPSEC failures that compromise engagements",
          "Lab: domain categorization + reputation checking for phishing domains",
          "Lab: email spoofing + SPF/DKIM/DMARC bypass techniques",
          "Lab: redirector setup with Apache mod_rewrite",
          "Lab: HTTPS redirector with nginx + Let's Encrypt",
          "Lab: domain fronting concept (CDN-based C2 traffic hiding)",
          "Lab: C2 traffic profiling — make beacon traffic look legitimate",
          "Study: anonymity and attribution — VPNs, Tor, operational separation",
          "Lab: OpSec checklist — build your own pre-engagement OpSec checklist",
          "Project: Full phishing campaign report — infrastructure + lure + results + detections",
        ]
      },
      {
        topic: "Web Application Exploitation (Advanced)",
        days: 25,
        tasks: [
          "SQLi: UNION-based extraction — database enumeration",
          "SQLi: blind boolean-based — extract data bit by bit",
          "SQLi: time-based blind — extract data via delays",
          "SQLi: second-order injection",
          "SQLi: out-of-band via DNS (xxe + sql combo)",
          "SQLi: WAF bypass techniques — encoding, comments, case variation",
          "XSS: DOM-based XSS — identify sinks and sources",
          "XSS: XSS to CSRF — combine for account takeover",
          "XSS: Content Security Policy bypass",
          "XSS: XSS in JSON context — encoded payloads",
          "SSRF: basic SSRF — probe internal services",
          "SSRF: blind SSRF via out-of-band DNS",
          "SSRF: SSRF to RCE via metadata endpoint (AWS/GCP)",
          "SSRF: SSRF filter bypass — IP encoding, redirects",
          "XXE: basic file read via XXE",
          "XXE: blind XXE via OOB DNS",
          "XXE: XXE via SVG upload",
          "Deserialization: Java deserialization with ysoserial",
          "Deserialization: PHP object injection",
          "IDOR: parameter manipulation — access other users' data",
          "JWT: algorithm confusion (none + RS256 to HS256)",
          "JWT: JWT secret cracking",
          "Path traversal: read /etc/passwd via ../../../../",
          "File upload: polyglot files — JPEG+PHP shell",
          "Project: Full web app penetration test report on a lab target — GitHub",
        ]
      },
      {
        topic: "Pivoting, Tunneling & C2 Basics",
        days: 20,
        tasks: [
          "Study: pivoting concepts — why and when pivoting is needed",
          "Lab: SSH local port forwarding — access an internal service",
          "Lab: SSH remote port forwarding — expose internal service externally",
          "Lab: SSH dynamic forwarding — SOCKS proxy through SSH tunnel",
          "Lab: proxychains configuration — route tools through SOCKS proxy",
          "Lab: chisel TCP tunneling — client/server setup",
          "Lab: plink.exe — SSH tunneling from Windows host",
          "Lab: socat relay — port forwarding without SSH",
          "Lab: multi-hop pivot — 3-segment network compromise",
          "Lab: DNS tunneling — exfiltrate data via DNS queries",
          "Lab: ICMP tunneling — ptunnel-ng data over ICMP",
          "Lab: HTTP tunneling through a web proxy",
          "Lab: Cobalt Strike basics — listener setup, beacon delivery",
          "Lab: Cobalt Strike — basic post-exploitation commands",
          "Lab: Havoc C2 — setup and first beacon",
          "Lab: C2 sleep + jitter configuration — avoid periodic detection",
          "Lab: C2 Malleable profiles — change traffic appearance",
          "Lab: SMB beacon — pivot C2 traffic through internal hosts",
          "Lab: map a C2 beacon's network traffic in Wireshark — know what blue sees",
          "Project: 3-hop pivot lab — documented methodology + network diagram",
        ]
      },
      {
        topic: "Pentest Report Writing",
        days: 10,
        tasks: [
          "Study: anatomy of a professional pentest report — executive summary vs technical",
          "Study: CVSS scoring — calculate scores for 5 real findings",
          "Lab: write an executive summary for your AD lab engagement",
          "Lab: write 3 finding write-ups: description + evidence + risk + remediation",
          "Lab: screenshot standards — redaction, annotations, captions",
          "Lab: risk ratings — Critical/High/Medium/Low — apply to your findings",
          "Lab: remediation section — actionable, prioritized, owner-assigned",
          "Lab: write a full methodology section",
          "Lab: peer review — critique a sample report from a public bug bounty",
          "Project: Complete professional pentest report for your AD lab engagement — PDF output",
        ]
      },
      {
        topic: "HackTheBox & CTF Practice",
        days: 25,
        tasks: [
          "HTB: Complete Active (Windows AD machine) — full write-up",
          "HTB: Complete Forest (Windows AD machine) — full write-up",
          "HTB: Complete Sauna (Windows AD machine) — full write-up",
          "HTB: Complete Monteverde (Windows AD machine) — full write-up",
          "HTB: Complete Remote (Windows) — full write-up",
          "HTB: Complete ServMon (Windows) — full write-up",
          "HTB: Complete OpenAdmin (Linux) — full write-up",
          "HTB: Complete Magic (Linux) — full write-up",
          "HTB: Complete Ready (Linux — Docker escape) — full write-up",
          "HTB: Complete Luanne (Linux) — full write-up",
          "CTF: Complete a web-focused CTF (PicoCTF or CTFtime selection)",
          "Review all write-ups — identify gaps in methodology",
          "HTB: Complete 3 additional machines of your choice",
          "PNPT Preparation: complete TCM AD course",
          "PNPT Preparation: practice exam environment",
          "Project: Publish all 10 HTB write-ups as GitHub Pages posts",
          "PNPT: Sit the exam",
          "Post-exam: review weak areas identified during exam",
          "HTB: Complete 2 more machines in weak area topics",
          "Project: Update GitHub profile with all completed write-ups and tools",
          "Review Phase 2 — identify 3 areas needing more depth",
          "Deep dive: 2 days on first identified gap",
          "Deep dive: 2 days on second identified gap",
          "Deep dive: 1 day on third identified gap",
          "Phase 2 retrospective: document key learnings, publish as blog post",
        ]
      },
    ]
  },

  // PHASE 3: Defensive Mastery (Days 281–400)
  {
    phase: 3,
    phaseLabel: "Defensive Mastery",
    color: "#60a5fa",
    blocks: [
      {
        topic: "Digital Forensics & Incident Response",
        days: 30,
        tasks: [
          "DFIR: disk forensics fundamentals — file systems, MFT, timestamps, slack space",
          "DFIR: FTK Imager — create a forensic image of a test drive",
          "DFIR: Autopsy — analyze a disk image, recover deleted files",
          "DFIR: Windows artifact analysis — prefetch, shellbags, registry hives",
          "DFIR: browser forensics — history, downloads, cached credentials",
          "DFIR: LNK file analysis — pivot on recent file access",
          "DFIR: memory forensics intro — Volatility3 setup",
          "DFIR: Volatility3 — list processes, identify suspicious ones",
          "DFIR: Volatility3 — identify injected DLLs + shellcode",
          "DFIR: Volatility3 — extract a C2 beacon from memory",
          "DFIR: Volatility3 — recover NTLM hashes from lsass",
          "DFIR: network forensics — pcap analysis for C2 traffic",
          "DFIR: Velociraptor — agent deployment + artifact collection",
          "DFIR: Velociraptor — live triage queries",
          "DFIR: build a triage checklist — first 30 minutes of an IR",
          "IR: containment strategies — isolate vs monitor tradeoffs",
          "IR: eradication — remove persistence, patch vuln, reset credentials",
          "IR: lessons learned — what to document after every incident",
          "IR simulation: given a compromised Windows host, build the full timeline",
          "IR simulation: given AD logs, reconstruct an attacker's lateral movement",
          "IR simulation: identify C2 beacon traffic in network logs",
          "IR simulation: full exercise — compromised AD from alert to report",
          "DFIR: mobile forensics intro — iOS/Android artifacts overview",
          "DFIR: log2timeline + plaso — build a super-timeline",
          "DFIR: Chainsaw — fast Windows event log analysis",
          "Project: Full IR report for a simulated incident — executive + technical — GitHub",
          "BTL1 preparation: review Blue Team Labs Online content",
          "BTL1 preparation: practice labs on BTLO platform",
          "BTL1: Sit the exam",
          "Post-BTL1: document gaps + plan remediation",
        ]
      },
      {
        topic: "Malware Analysis",
        days: 25,
        tasks: [
          "Malware analysis: set up isolated analysis VM — no internet, snapshots",
          "Static analysis: strings, file type identification, hashing",
          "Static analysis: PE format deep dive — headers, sections, imports",
          "Static analysis: identify suspicious imports (VirtualAlloc, WriteProcessMemory)",
          "Static analysis: packing detection — entropy analysis",
          "Static analysis: Ghidra setup — first binary analysis",
          "Static analysis: Ghidra — analyze a simple malware dropper",
          "Static analysis: Ghidra — identify C2 configuration in binary",
          "Dynamic analysis: ANY.RUN — analyze Emotet sample",
          "Dynamic analysis: Cuckoo sandbox setup + analyze a sample",
          "Dynamic analysis: process monitor — trace file/registry changes",
          "Dynamic analysis: Wireshark during execution — identify C2 traffic",
          "Dynamic analysis: API Monitor — trace Windows API calls",
          "YARA: write your first YARA rule to detect a specific malware family",
          "YARA: YARA rule for a string + PE characteristic combination",
          "YARA: test YARA rules against a sample set — measure FP/FN rate",
          "Analysis: Qakbot sample — full static + dynamic analysis report",
          "Analysis: Cobalt Strike beacon — extract C2 config from memory dump",
          "Analysis: ransomware sample (academic) — document encryption mechanism",
          "Analysis: rootkit sample — identify hiding techniques",
          "Analysis: document the difference between dropper, loader, payload, C2",
          "YARA: write 5 rules targeting the malware families you analyzed",
          "Detection: build SIEM detections from your malware analysis findings",
          "Project: Full malware analysis report for 3 samples — published on GitHub",
          "Project: YARA rule set for identified malware families — submitted to VirusTotal",
        ]
      },
      {
        topic: "Detection Engineering & Purple Team",
        days: 35,
        tasks: [
          "Study: Sigma rule format — understand all fields, modifiers, conditions",
          "Sigma: write your first rule — PowerShell encoded command detection",
          "Sigma: Kerberoasting detection rule",
          "Sigma: NTLM relay detection rule",
          "Sigma: DCSync detection rule (Event ID 4662 + 4769)",
          "Sigma: lateral movement via WMI detection",
          "Sigma: lateral movement via PSExec detection",
          "Sigma: persistence via Run keys detection",
          "Sigma: credential dumping via lsass access detection",
          "Sigma: Mimikatz detection via multiple patterns",
          "Sigma: BloodHound SharpHound enumeration detection",
          "Sigma: convert all rules to Splunk SPL — test against your Phase 2 logs",
          "Sigma: submit 3 rules to SigmaHQ — open source contribution",
          "Detection: build a detection for every Phase 2 technique — coverage matrix",
          "Purple Team Labs v1 — complete all exercises",
          "Purple Team: AD attack/detect cycle — run attack, verify detection, improve rule",
          "Purple Team: Azure AD attack/detect cycle",
          "Purple Team: VECTR setup — document your purple team exercises",
          "Purple Team: MITRE ATT&CK coverage mapping — visualize your detection coverage",
          "Detection: ATT&CK Navigator heatmap — export your coverage",
          "Detection: identify top 5 undetected techniques in your environment",
          "Detection: build detections for the 5 undetected techniques",
          "Threat hunting: hypothesis — 'attacker has a Cobalt Strike beacon active'",
          "Threat hunting: hypothesis — 'attacker is performing Kerberoasting'",
          "Threat hunting: hypothesis — 'attacker is doing LDAP reconnaissance'",
          "Threat hunting: build a hunting playbook — 5 hypotheses with methodology",
          "Detection: false positive tuning — reduce noise in 3 of your existing rules",
          "Detection: build a Splunk dashboard showing your full detection coverage",
          "Study: ATT&CK D3FEND — understand the defensive countermeasure framework",
          "Project: Detection engineering portfolio — 20 Sigma rules + ATT&CK coverage map",
          "Project: Purple team exercise report — 5 attack/detect cycles documented",
          "Review Phase 3 — identify gaps, plan Phase 4 with clear objectives",
          "Phase 3 retrospective: blog post — 'How I built detection for everything I attacked'",
          "EDR internals: understand Windows kernel callbacks used by EDR",
          "EDR internals: trace how CrowdStrike detects a Mimikatz execution",
        ]
      },
      {
        topic: "SIEM Engineering Deep Dive",
        days: 10,
        tasks: [
          "Splunk: advanced SPL — stats, eventstats, transaction, lookup",
          "Splunk: build a threat hunting dashboard from scratch",
          "Splunk: correlation searches — multi-event alerts",
          "Splunk: BOTS dataset — complete Season 1 investigation",
          "Elastic: EQL (Event Query Language) — write 5 hunting queries",
          "Elastic: detection rules — port your Sigma rules to Elastic",
          "Elastic: Endpoint Security — configure and analyze EDR events",
          "Build: end-to-end pipeline — Sysmon → Winlogbeat → Elastic → Kibana dashboard",
          "Build: Logstash filter pipeline — parse and enrich Windows event logs",
          "Project: SIEM engineering write-up — your full detection pipeline documented",
        ]
      },
    ]
  },

  // PHASE 4: Advanced Tradecraft (Days 401–580)
  {
    phase: 4,
    phaseLabel: "Advanced Tradecraft",
    color: "#fb923c",
    blocks: [
      {
        topic: "AV/EDR Evasion Engineering",
        days: 35,
        tasks: [
          "Study: Windows security mechanisms — AMSI, ETW, Windows Defender internals",
          "Study: How AV scanning works — static, dynamic, behavioral, ML",
          "Lab: AMSI bypass via memory patching — patch AmsiScanBuffer",
          "Lab: AMSI bypass via reflection — obfuscate the bypass itself",
          "Lab: ETW patching — blind EDR telemetry",
          "Lab: unhooking NTDLL — restore clean syscall stubs",
          "Lab: direct syscalls — bypass userland hooks with syscall instruction",
          "Lab: indirect syscalls — halosgate / tartarusgate techniques",
          "Lab: PE reflective loading — load a DLL without LoadLibrary",
          "Lab: process injection — classic CreateRemoteThread + VirtualAllocEx",
          "Lab: process injection — QueueUserAPC injection",
          "Lab: process injection — early bird injection",
          "Lab: process injection — thread hijacking",
          "Lab: process hollowing — replace a legitimate process image",
          "Lab: DLL sideloading — find a vulnerable signed application",
          "Lab: sleep masking — obfuscate implant in memory during sleep",
          "Lab: Ekko sleep mask — ROT13 + timer-based encryption",
          "Lab: Foliage / Ekko comparison — understand multiple sleep masking approaches",
          "Lab: stack spoofing — hide your implant's call stack",
          "Lab: payload encoding — custom XOR + RC4 encryption",
          "Lab: packer development — write a simple PE packer in C",
          "Lab: ScareCrow — weaponized payload generation with evasion built-in",
          "Lab: Donut — position-independent shellcode from .NET assemblies",
          "Lab: test all techniques against Windows Defender in lab",
          "Lab: test techniques against a commercial EDR (trial/lab license)",
          "Lab: Evasion Labs platform — complete all exercises",
          "Lab: identify EDR kernel callbacks your techniques trigger",
          "Lab: build a detection bypass matrix — technique + EDR response + bypass",
          "Study: PE format deep dive — optional headers, data directories, TLS callbacks",
          "Study: Windows loader — how DLLs are loaded, IAT, relocations",
          "Lab: manual IAT parsing — resolve imports without LoadLibrary",
          "Lab: position-independent shellcode — write a PIC dropper",
          "Lab: compile with LLVM obfuscator — observe entropy + string changes",
          "Lab: anti-analysis — anti-debugging, anti-VM, sandbox detection",
          "Project: Full evasion research write-up — bypass chain against a named EDR",
        ]
      },
      {
        topic: "Windows Kernel & Low-Level Development",
        days: 30,
        tasks: [
          "Kernel: Windows architecture — user mode vs kernel mode, rings",
          "Kernel: kernel objects — EPROCESS, ETHREAD, PEB, TEB",
          "Kernel: Windows driver model — WDM, WDF, driver types",
          "Lab: set up kernel debugging — WinDBG + VMware/Hyper-V",
          "Lab: load a simple KMDF driver — Hello World from kernel",
          "Lab: enumerate processes from kernel — walk EPROCESS list",
          "Lab: hide a process from kernel — DKOM (Direct Kernel Object Manipulation)",
          "Lab: kernel callback routines — PsSetCreateProcessNotifyRoutine",
          "Lab: kernel callback routines — ObRegisterCallbacks",
          "Lab: intercept and block operations via kernel callbacks",
          "Lab: kernel memory — VirtualQuery, read/write across processes",
          "Lab: minifilter driver — intercept file operations",
          "Lab: Windows kernel exploitation — study a CVE (e.g., CVE-2021-31956)",
          "Lab: privilege escalation via kernel exploit in lab",
          "Lab: token manipulation from kernel — steal SYSTEM token",
          "Study: kernel patch protection (PatchGuard) — understand, not bypass",
          "Study: Secure Boot + UEFI — implications for kernel rootkits",
          "Lab: driver signing bypass in lab environment (test mode)",
          "Lab: BYOVD (Bring Your Own Vulnerable Driver) concept",
          "Lab: exploit a vulnerable kernel driver in lab",
          "Windows API: Win32 API reference — key subsystems for offensive dev",
          "Windows API: NTAPI — Nt*/Zw* functions, NtAllocateVirtualMemory",
          "Windows API: Windows internals book — read relevant chapters",
          "Red Team Windows API course — complete all modules",
          "Lab: NtCreateThreadEx — create thread avoiding CreateRemoteThread hooks",
          "Lab: NtMapViewOfSection — map shellcode using section objects",
          "Lab: NTFS ADS — hide data in alternate data streams",
          "Lab: token impersonation from user mode — SeImpersonatePrivilege",
          "Lab: handle duplication — duplicate handles across processes",
          "Project: Kernel rootkit that hides a process + its network connections — documented",
        ]
      },
      {
        topic: "C2 Development & BOF Engineering",
        days: 35,
        tasks: [
          "Study: C2 architecture — implant, listener, team server, operator interface",
          "Study: C2 comms — HTTP, HTTPS, DNS, SMB, raw TCP — trade-offs",
          "Lab: implement a TCP reverse shell in C — understand every socket call",
          "Lab: add task queue to your C2 — polling model",
          "Lab: HTTP C2 — beacon polls HTTP endpoint for commands",
          "Lab: HTTPS C2 — add TLS with self-signed cert",
          "Lab: C2 command handling — execute shell, upload, download, sleep",
          "Lab: C2 in-memory execution — run shellcode from operator",
          "Lab: C2 process injection capability",
          "Lab: C2 persistence mechanism — install as service or scheduled task",
          "Lab: C2 in Rust — port your HTTP C2 to Rust for better OPSEC",
          "Lab: C2 staging — stager downloads second-stage from URL",
          "Lab: C2 domain fronting simulation in lab",
          "BOF: BOF development environment setup — Cobalt Strike BOF template",
          "BOF: write BOF #1 — execute whoami and return output",
          "BOF: write BOF #2 — enumerate running services",
          "BOF: write BOF #3 — add a local admin user",
          "BOF: write BOF #4 — dump credentials from Credential Manager",
          "BOF: write BOF #5 — inject shellcode into a remote process",
          "BOF: integrate your BOFs into a Cobalt Strike aggressor script",
          "Advanced C2: Cobalt Strike Malleable C2 profile — write a custom profile",
          "Advanced C2: Cobalt Strike team server — configure for multi-operator",
          "Advanced C2: C2 relay chain — HTTP redirector → team server",
          "Advanced C2: Cobalt Strike post-exploitation kit — custom VBA macro",
          "Red Team Offensive Agent course — complete all modules",
          "Red Team Development Lab — complete all exercises",
          "Lab: Havoc C2 internals — read source code of one component",
          "Lab: Sliver C2 — setup + explore as Cobalt Strike alternative",
          "Lab: C2 detection — run your custom C2 and try to detect it in Elastic",
          "Lab: purple team loop — C2 → EDR detection → evasion → detection improvement",
          "Project: Custom C2 implant published on GitHub with documentation",
          "Project: BOF collection — 5 original BOFs published open-source",
          "Lab: C2 infrastructure hardening — HTTPS + CDN + redirectors + domain aging",
          "Lab: Building Red Team Operations course — complete all modules",
          "Lab: Red Team Ops Platform — configure for team use",
        ]
      },
      {
        topic: "Offensive IAM & Cloud",
        days: 25,
        tasks: [
          "Cloud: AWS IAM fundamentals — users, roles, policies, STS",
          "Cloud: enumerate AWS IAM with compromised credentials",
          "Cloud: IAM privilege escalation — iam:PassRole + lambda",
          "Cloud: IAM privilege escalation — iam:CreateAccessKey on other users",
          "Cloud: S3 bucket enumeration + misconfigurations",
          "Cloud: EC2 metadata service — steal IAM credentials via SSRF",
          "Cloud: Pacu — AWS attack framework, run 10 modules",
          "Cloud: Azure RBAC — enumerate with AzureHound",
          "Cloud: Azure privilege escalation — subscription contributor",
          "Cloud: Azure managed identity abuse",
          "Cloud: GCP IAM — workload identity federation abuse",
          "Cloud: cross-cloud — pivot from AWS to Azure via federated identity",
          "Offensive IAM Exploitation course — complete all modules",
          "Lab: build a detection for each IAM attack in AWS CloudTrail",
          "Lab: build detections for Azure AD sign-in logs",
          "Secure Code Review — methodology: data flow, trust boundaries, sink analysis",
          "Code review: review a PHP application — find 3 vulnerability classes",
          "Code review: review a Node.js application — find injection + auth flaws",
          "Code review: review a Python Flask application",
          "Code review: review a Java Spring application",
          "Code review: SAST tools — run Semgrep against a vulnerable application",
          "White Box Testing course — complete all modules",
          "Lab: combine SAST + manual review — find what automated tools miss",
          "Lab: write a vulnerability report from a code review — developer-audience",
          "Project: Code review + vulnerability report for an open-source application",
        ]
      },
      {
        topic: "OSCP Preparation & Exam",
        days: 30,
        tasks: [
          "OSCP prep: review PEN-200 course — identify weak areas",
          "OSCP prep: practice buffer overflows — x86 Windows DEP disabled",
          "OSCP prep: 5 HTB TJ Null list machines — document all",
          "OSCP prep: 5 more HTB TJ Null list machines",
          "OSCP prep: 5 more HTB TJ Null list machines",
          "OSCP prep: Proving Grounds Practice — 5 machines",
          "OSCP prep: Proving Grounds Practice — 5 more machines",
          "OSCP prep: timed practice — complete 3 machines in 4 hours",
          "OSCP prep: note-taking system — optimize Obsidian/CherryTree for exam",
          "OSCP prep: report template — prepare your exam report template",
          "OSCP prep: final review — Active Directory attack chains",
          "OSCP: Sit the 24-hour exam",
          "OSCP: write and submit the exam report (24-hour window)",
          "Post-OSCP: review exam performance — document lessons",
          "Post-OSCP: celebrate, then identify next target (CRTO)",
          "CRTO: complete Cobalt Strike Red Team Ops course",
          "CRTO: complete all lab exercises",
          "CRTO: sit the exam",
          "CRTE: complete course material",
          "CRTE: complete all AD lab exercises",
          "CRTE: sit the exam",
          "Post-certs: publish a blog post — 'My OSCP + CRTO + CRTE journey'",
          "Phase 4 retrospective: document key technical learnings",
          "Phase 4 gaps: identify top 3 areas needing more depth",
          "Phase 4 deep dive 1: 2 days on first gap",
          "Phase 4 deep dive 2: 2 days on second gap",
          "Phase 4 deep dive 3: 1 day on third gap",
          "Portfolio update: README, pinned repos, bio",
          "LinkedIn update: add certs, projects, skills",
          "Job market check: research senior red team / purple team job requirements",
          "Networking: connect with 5 practitioners in your target companies",
        ]
      },
    ]
  },

  // PHASE 5: Specialization (Days 581–700)
  {
    phase: 5,
    phaseLabel: "Specialization",
    color: "#c084fc",
    blocks: [
      {
        topic: "ICS/SCADA Security",
        days: 30,
        tasks: [
          "ICS: fundamentals — OT vs IT, SCADA, DCS, PLC, HMI components",
          "ICS: protocols — Modbus, DNP3, IEC 61850, OPC-UA",
          "ICS: network architecture — Purdue model, ISA/IEC 62443 zones",
          "ICS: threat landscape — Stuxnet, Industroyer, TRITON — case studies",
          "Lab: ScadaBR setup — simulate an industrial environment",
          "Lab: Modbus traffic analysis with Wireshark",
          "Lab: exploit a simulated PLC misconfiguration",
          "ICS: vulnerability research — common ICS CVEs, ICS-CERT advisories",
          "ICS: attack methodology — passive recon → network mapping → exploitation",
          "ICS: Shodan for ICS — find exposed industrial systems (observe only)",
          "ICS: network segmentation assessment — identify missing controls",
          "ICS: ICS-specific malware — Industroyer2 analysis",
          "ICS: defense — network monitoring with Claroty/Dragos concepts",
          "ICS: incident response — different from IT IR (don't just shut things down)",
          "ICS: ISA/IEC 62443 standard — security levels, zones and conduits",
          "Lab: threat model a water treatment plant simulation",
          "Lab: Conpot honeypot — understand attacker TTPs against ICS",
          "Lab: write an ICS security assessment report",
          "Lab: detection rules for ICS-specific attack patterns",
          "Lab: ICS network traffic baseline — identify anomalies",
          "ICS: wireless in industrial environments — WirelessHART, ISA100.11a",
          "ICS: safety systems — SIS, SIL levels, why TRITON was significant",
          "ICS: cloud-connected OT — attack surface expansion",
          "Lab: full ICS assessment simulation — document methodology and findings",
          "Lab: ICS red team report — present to a fictional safety + security audience",
          "ICS: GICSP exam prep — review study materials",
          "ICS: GICSP practice questions",
          "ICS: sit GICSP exam (if pursuing this path)",
          "Project: ICS security assessment report published (redacted lab environment)",
          "Project: Blog post — 'What a penetration tester needs to know about ICS'",
        ]
      },
      {
        topic: "iOS & macOS Internals",
        days: 30,
        tasks: [
          "iOS: architecture — XNU kernel, sandboxing, entitlements, codesigning",
          "iOS: app structure — IPA format, plist, Mach-O binaries",
          "iOS: Frida setup on a jailbroken iOS device or simulator",
          "iOS: objection — runtime exploration without jailbreak",
          "iOS: SSL pinning bypass with Frida script",
          "iOS: extract data from an iOS app — NSUserDefaults, Keychain, SQLite",
          "iOS: static analysis with MobSF",
          "iOS: reverse engineer a simple iOS app with Ghidra (ARM64)",
          "iOS: identify 3 vulnerability classes in a test app",
          "iOS: URL scheme hijacking",
          "iOS: UIWebView XSS",
          "iOS: insecure data storage — find credentials in plaintext",
          "iOS: iOS & macOS Internals course — complete all modules",
          "macOS: system architecture — XPC, launch daemons, launch agents",
          "macOS: persistence mechanisms — LaunchDaemons, LaunchAgents, login items",
          "macOS: TCC (Transparency, Consent, Control) — privacy framework",
          "macOS: Gatekeeper + notarization — bypass techniques",
          "macOS: code signing — understand entitlements",
          "macOS: DYLD injection — hijack library loading",
          "macOS: endpoint security framework — how macOS EDR works",
          "macOS: AppleScript + osascript for offense",
          "macOS: common macOS CVEs — case study two recent ones",
          "Lab: build a macOS persistence mechanism — LaunchAgent",
          "Lab: bypass TCC in lab to access camera/mic (ethical, local only)",
          "Lab: macOS privilege escalation — SUID + sudo misconfigs",
          "Lab: analyze macOS malware sample (Shlayer or similar)",
          "Lab: write YARA rules for a macOS malware family",
          "Lab: macOS IR — collect and analyze key artifacts",
          "Project: iOS app vulnerability assessment report — test application",
          "Project: macOS persistence + detection write-up — published blog post",
        ]
      },
      {
        topic: "AI/LLM Security & Offensive AI",
        days: 30,
        tasks: [
          "AI security: LLM fundamentals — transformers, tokens, context windows",
          "AI security: threat model for LLM applications",
          "AI security: prompt injection — direct vs indirect injection",
          "AI security: prompt injection — exfiltrate system prompt",
          "AI security: prompt injection — hijack LLM in an agentic workflow",
          "AI security: jailbreaking — bypass safety training",
          "AI security: model extraction — reconstruct model behavior via queries",
          "AI security: data poisoning — understand training data attacks",
          "AI security: RAG (Retrieval Augmented Generation) attacks",
          "AI security: vector database poisoning",
          "AI security: OWASP LLM Top 10 — study all 10",
          "Master Prompt Engineering course — complete all modules",
          "Intro to Offensive Security with AI — complete all modules",
          "Lab: set up a vulnerable LLM application (WebGoat-LLM or similar)",
          "Lab: execute 5 prompt injection attacks — document with screenshots",
          "Lab: extract system prompt from a black-box LLM API",
          "Lab: build a LLM-powered recon assistant — automate with Python + OpenAI API",
          "Lab: LLM-assisted payload generation — use AI to generate obfuscated code",
          "Lab: LLM-assisted report writing — draft a finding description from notes",
          "Lab: AI-powered phishing email generation — understand the risk",
          "Lab: build a simple LLM security testing framework in Python",
          "Lab: AI security detection — write rules to detect prompt injection in logs",
          "Lab: benchmark an LLM's safety responses — document failure modes",
          "Lab: responsible disclosure — research a real LLM application for vulns",
          "Study: AI governance — EU AI Act, NIST AI RMF overview",
          "Study: adversarial ML — FGSM, PGD attacks on image classifiers",
          "Lab: evasion attack on a simple ML-based malware classifier",
          "Lab: poisoning attack on a simple intrusion detection model",
          "Project: LLM security research write-up — 5 novel attack scenarios with mitigations",
          "Project: Blog post — 'How to red team an LLM application'",
        ]
      },
      {
        topic: "Bug Bounty & Vulnerability Research",
        days: 20,
        tasks: [
          "Bug bounty: methodology — scope review, recon, prioritization",
          "Bug bounty: target selection — pick first real program (HackerOne / Bugcrowd)",
          "Bug bounty: passive recon — subdomain enumeration, tech stack ID",
          "Bug bounty: active recon — endpoint discovery, parameter discovery",
          "Bug bounty: authentication testing — OAuth, SSO, MFA bypass attempts",
          "Bug bounty: access control testing — IDOR, privilege escalation",
          "Bug bounty: business logic testing — understand the application flow",
          "Bug bounty: 4 days focused testing on target — document all findings",
          "Bug bounty: write first submission — even if Low/Informational",
          "Bug bounty: triage feedback — analyze rejection or acceptance",
          "Bug bounty: second target — apply lessons from first",
          "Bug bounty: 4 more days focused testing — aim for a Medium or High",
          "Bug bounty: vulnerability chaining — combine two low-severity issues",
          "CVE research: study the CVE submission process",
          "CVE research: identify a potential vulnerability in an open-source project",
          "CVE research: write a proof-of-concept exploit",
          "CVE research: responsible disclosure — contact maintainer",
          "CVE research: document the process regardless of outcome",
          "Red Team Adaptive Operations — complete all modules",
          "Project: Publish bug bounty write-up (if disclosure allowed by program)",
        ]
      },
    ]
  },

  // PHASE 6: Elite Purple Team (Days 701–800)
  {
    phase: 6,
    phaseLabel: "Elite Purple Team",
    color: "#f472b6",
    blocks: [
      {
        topic: "Full Purple Team Engagements",
        days: 40,
        tasks: [
          "Purple team: engagement planning — scope, rules of engagement, success criteria",
          "Purple team: threat intelligence — identify relevant threat actors for target sector",
          "Purple team: threat actor emulation — map TTPs to ATT&CK",
          "Purple team: Caldera setup — automated adversary emulation",
          "Purple team: build ATT&CK-based test plan — 20 techniques to test",
          "Purple team engagement 1: phase 1 — initial access simulation",
          "Purple team engagement 1: phase 2 — lateral movement simulation",
          "Purple team engagement 1: phase 3 — detection verification",
          "Purple team engagement 1: phase 4 — detection improvement",
          "Purple team engagement 1: phase 5 — re-test after improvement",
          "Purple team engagement 1: write executive report",
          "Purple team engagement 1: write technical appendix",
          "Purple team engagement 1: VECTR documentation — full engagement logged",
          "Purple team engagement 2: different threat actor emulation",
          "Purple team engagement 2: focus on cloud + hybrid AD",
          "Purple team engagement 2: focus on exfiltration techniques",
          "Purple team engagement 2: detection verification cycle",
          "Purple team engagement 2: full report",
          "Security architecture: threat modeling methodology — STRIDE + PASTA",
          "Security architecture: design a secure cloud architecture for a fictional company",
          "Security architecture: threat model a microservices application",
          "Security architecture: TIBER-EU framework — study the methodology",
          "Security architecture: write a defensive architecture document",
          "Pentest & Report Writing course — complete all modules",
          "Executive communication: present your purple team findings to a non-technical audience",
          "Adversary emulation: APT29 (Cozy Bear) TTP campaign in lab",
          "Adversary emulation: APT41 TTP campaign in lab",
          "Adversary emulation: FIN7 TTP campaign in lab",
          "Threat intelligence: MISP setup — import a threat intelligence feed",
          "Threat intelligence: write a threat intelligence report on an APT group",
          "Threat intelligence: intelligence-driven purple team — use CTI to prioritize testing",
          "Cyber Security Architecture course — complete all modules",
          "Build: security program recommendation document for a fictional mid-size org",
          "Build: detection engineering runbook — onboarding guide for a new analyst",
          "Mentorship: document and explain 5 techniques to a fictional junior analyst",
          "Mentorship: write a 'how to get started in purple teaming' guide",
          "Conference: prepare a 20-minute talk proposal for a security conference",
          "Conference: submit talk to BSides or regional DEFCON village",
          "Portfolio: final review — ensure all projects are documented and public",
          "Portfolio: write a portfolio summary blog post",
        ]
      },
      {
        topic: "Career & Professional Development",
        days: 30,
        tasks: [
          "Job search: identify 10 target companies — research each",
          "Job search: identify 5 target roles at each company",
          "Resume: tailor resume for Senior Red Team / Purple Team roles",
          "LinkedIn: optimize profile — keywords, projects, certs, recommendations",
          "Networking: reach out to 5 practitioners at target companies",
          "Networking: attend a virtual security conference or meetup",
          "Interview prep: system design — design a detection system for APT intrusion",
          "Interview prep: technical — explain DCSync, detection, and remediation",
          "Interview prep: technical — explain EDR bypass techniques conceptually",
          "Interview prep: behavioral — prepare STAR stories for your portfolio projects",
          "Interview prep: code interview — Python scripting challenge practice",
          "Job applications: apply to 5 senior roles",
          "Job applications: apply to 5 more senior roles",
          "Interview: complete 2 technical phone screens",
          "Interview: complete 1 technical panel interview",
          "Negotiation: research salary ranges for target roles",
          "CRTL: complete Red Team Lead course",
          "CRTL: sit the exam",
          "Phase 6 retrospective: document the full 800-day journey",
          "Blog: write 'What I learned in 800 days of cybersecurity'",
          "Final portfolio audit: every project README is complete and professional",
          "GitHub profile: pinned repos, clear descriptions, contribution graph active",
          "LinkedIn: publish a post about completing the 800-day roadmap",
          "Celebrate: you are now hard to replace",
          "Plan: what does year 2 look like? CVE research? Conference talks? Leadership?",
          "Plan: identify 3 areas for continued growth beyond the roadmap",
          "Mentor: find a beginner to mentor — teach what you've learned",
          "Contribute: submit a PR to an open-source security tool",
          "Write: final comprehensive blog post — your complete purple team methodology",
          "Day 800: reflection — compare Day 1 you vs Day 800 you",
        ]
      },
    ]
  },
];

// ── Generate flat day array ───────────────────────────────────────────────────
function generateRoadmap() {
  const days = [];
  let dayCounter = 1;

  for (const phase of PHASE_CONTENT) {
    for (const block of phase.blocks) {
      let taskIndex = 0;
      for (let d = 0; d < block.days; d++) {
        const isSunday = (dayCounter - 1) % 7 === 6;
        const tasksForDay = isSunday ? 2 : 1;
        const dayTasks = [];

        for (let t = 0; t < tasksForDay && taskIndex < block.tasks.length; t++) {
          dayTasks.push({
            id: `d${dayCounter}-t${t + 1}`,
            text: block.tasks[taskIndex],
            points: 5,
            completed: false,
          });
          taskIndex++;
        }

        if (dayTasks.length === 0 && block.tasks.length > 0) {
          dayTasks.push({
            id: `d${dayCounter}-t1`,
            text: block.tasks[block.tasks.length - 1],
            points: 5,
            completed: false,
          });
        }

        days.push({
          day: dayCounter,
          phase: phase.phase,
          phaseLabel: phase.phaseLabel,
          phaseColor: phase.color,
          topic: block.topic,
          tasks: dayTasks,
          isSunday,
          hours: isSunday ? 6 : 4,
          scoreMultiplier: isSunday ? 1.5 : 1.0,
        });

        dayCounter++;
        if (dayCounter > 800) break;
      }
      if (dayCounter > 800) break;
    }
    if (dayCounter > 800) break;
  }

  // Fill remaining days if needed
  while (days.length < 800) {
    const dayNum = days.length + 1;
    const isSunday = (dayNum - 1) % 7 === 6;
    days.push({
      day: dayNum,
      phase: 6,
      phaseLabel: "Elite Purple Team",
      phaseColor: "#f472b6",
      topic: "Advanced Practice & Research",
      tasks: [{
        id: `d${dayNum}-t1`,
        text: "Continue advanced research and portfolio development",
        points: 5,
        completed: false,
      }],
      isSunday,
      hours: isSunday ? 6 : 4,
      scoreMultiplier: isSunday ? 1.5 : 1.0,
    });
  }

  return { days, generatedAt: new Date().toISOString(), totalDays: days.length };
}

const roadmap = generateRoadmap();
const outputPath = join(__dirname, '..', 'src', 'data', 'roadmap.json');
writeFileSync(outputPath, JSON.stringify(roadmap, null, 2));
console.log(`✅ Generated ${roadmap.days.length} days → src/data/roadmap.json`);
